package com.fintech.oracle.dataabstraction.entities;
// Generated Dec 5, 2016 6:07:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OcrExtractionField generated by hbm2java
 */
@Entity
@Table(name="ocr_extraction_field"
)
public class OcrExtractionField  implements java.io.Serializable {


     private int id;
     private String field;
     private Set<OcrResults> ocrResultses = new HashSet<OcrResults>(0);

    public OcrExtractionField() {
    }

	
    public OcrExtractionField(int id) {
        this.id = id;
    }
    public OcrExtractionField(int id, String field, Set<OcrResults> ocrResultses) {
       this.id = id;
       this.field = field;
       this.ocrResultses = ocrResultses;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="FIELD", length=50)
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ocrExtractionField")
    public Set<OcrResults> getOcrResultses() {
        return this.ocrResultses;
    }
    
    public void setOcrResultses(Set<OcrResults> ocrResultses) {
        this.ocrResultses = ocrResultses;
    }




}


