package com.fintech.oracle.dataabstraction.entities;
// Generated Dec 25, 2016 11:01:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OcrExtractionField generated by hbm2java
 */
@Entity
@Table(name="ocr_extraction_field"
    ,catalog="idapi"
)
public class OcrExtractionField  implements java.io.Serializable {


     private int id;
     private String field;
     private Set<ResourceNameOcrExtractionField> resourceNameOcrExtractionFields = new HashSet<ResourceNameOcrExtractionField>(0);

    public OcrExtractionField() {
    }

	
    public OcrExtractionField(int id) {
        this.id = id;
    }
    public OcrExtractionField(int id, String field, Set<ResourceNameOcrExtractionField> resourceNameOcrExtractionFields) {
       this.id = id;
       this.field = field;
       this.resourceNameOcrExtractionFields = resourceNameOcrExtractionFields;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="FIELD", length=50)
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ocrExtractionField")
    public Set<ResourceNameOcrExtractionField> getResourceNameOcrExtractionFields() {
        return this.resourceNameOcrExtractionFields;
    }
    
    public void setResourceNameOcrExtractionFields(Set<ResourceNameOcrExtractionField> resourceNameOcrExtractionFields) {
        this.resourceNameOcrExtractionFields = resourceNameOcrExtractionFields;
    }




}


