package com.fintech.oracle.dataabstraction.entities;
// Generated Nov 24, 2016 4:01:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OcrProcessType generated by hbm2java
 */
@Entity
@Table(name="ocr_process_type"
)
public class OcrProcessType  implements java.io.Serializable {


     private int id;
     private String type;
     private Set<OcrProcess> ocrProcesses = new HashSet<OcrProcess>(0);

    public OcrProcessType() {
    }

	
    public OcrProcessType(int id) {
        this.id = id;
    }
    public OcrProcessType(int id, String type, Set<OcrProcess> ocrProcesses) {
       this.id = id;
       this.type = type;
       this.ocrProcesses = ocrProcesses;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="TYPE", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ocrProcessType")
    public Set<OcrProcess> getOcrProcesses() {
        return this.ocrProcesses;
    }
    
    public void setOcrProcesses(Set<OcrProcess> ocrProcesses) {
        this.ocrProcesses = ocrProcesses;
    }




}


