package com.fintech.oracle.dataabstraction.entities;
// Generated Dec 5, 2016 6:07:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OcrProcess generated by hbm2java
 */
@Entity
@Table(name="ocr_process"
)
public class OcrProcess  implements java.io.Serializable {


     private Integer id;
     private OcrProcessingRequest ocrProcessingRequest;
     private OcrProcessingStatus ocrProcessingStatus;
     private OcrProcessType ocrProcessType;
     private Set<OcrResults> ocrResultses = new HashSet<OcrResults>(0);
     private Set<Resource> resources = new HashSet<Resource>(0);

    public OcrProcess() {
    }

	
    public OcrProcess(OcrProcessingRequest ocrProcessingRequest, OcrProcessingStatus ocrProcessingStatus, OcrProcessType ocrProcessType) {
        this.ocrProcessingRequest = ocrProcessingRequest;
        this.ocrProcessingStatus = ocrProcessingStatus;
        this.ocrProcessType = ocrProcessType;
    }
    public OcrProcess(OcrProcessingRequest ocrProcessingRequest, OcrProcessingStatus ocrProcessingStatus, OcrProcessType ocrProcessType, Set<OcrResults> ocrResultses, Set<Resource> resources) {
       this.ocrProcessingRequest = ocrProcessingRequest;
       this.ocrProcessingStatus = ocrProcessingStatus;
       this.ocrProcessType = ocrProcessType;
       this.ocrResultses = ocrResultses;
       this.resources = resources;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCESSING_REQUEST", nullable=false)
    public OcrProcessingRequest getOcrProcessingRequest() {
        return this.ocrProcessingRequest;
    }
    
    public void setOcrProcessingRequest(OcrProcessingRequest ocrProcessingRequest) {
        this.ocrProcessingRequest = ocrProcessingRequest;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCESSING_STATUS", nullable=false)
    public OcrProcessingStatus getOcrProcessingStatus() {
        return this.ocrProcessingStatus;
    }
    
    public void setOcrProcessingStatus(OcrProcessingStatus ocrProcessingStatus) {
        this.ocrProcessingStatus = ocrProcessingStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCESS_TYPE", nullable=false)
    public OcrProcessType getOcrProcessType() {
        return this.ocrProcessType;
    }
    
    public void setOcrProcessType(OcrProcessType ocrProcessType) {
        this.ocrProcessType = ocrProcessType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ocrProcess")
    public Set<OcrResults> getOcrResultses() {
        return this.ocrResultses;
    }
    
    public void setOcrResultses(Set<OcrResults> ocrResultses) {
        this.ocrResultses = ocrResultses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ocrProcess")
    public Set<Resource> getResources() {
        return this.resources;
    }
    
    public void setResources(Set<Resource> resources) {
        this.resources = resources;
    }




}


