package com.fintech.oracle.dataabstraction.entities;
// Generated Dec 25, 2016 11:01:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OcrResult generated by hbm2java
 */
@Entity
@Table(name="ocr_result"
)
public class OcrResult  implements java.io.Serializable {


     private Integer id;
     private OcrProcess ocrProcess;
     private ResourceNameOcrExtractionField resourceNameOcrExtractionField;
     private String value;
     private Double ocrConfidence;
     private String resultName;

    public OcrResult() {
    }

    public OcrResult(OcrProcess ocrProcess, ResourceNameOcrExtractionField resourceNameOcrExtractionField, String value, Double ocrConfidence, String resultName) {
       this.ocrProcess = ocrProcess;
       this.resourceNameOcrExtractionField = resourceNameOcrExtractionField;
       this.value = value;
       this.ocrConfidence = ocrConfidence;
       this.resultName = resultName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OCR_PROCESS")
    public OcrProcess getOcrProcess() {
        return this.ocrProcess;
    }
    
    public void setOcrProcess(OcrProcess ocrProcess) {
        this.ocrProcess = ocrProcess;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OCR_EXTRACTION_FIELD")
    public ResourceNameOcrExtractionField getResourceNameOcrExtractionField() {
        return this.resourceNameOcrExtractionField;
    }
    
    public void setResourceNameOcrExtractionField(ResourceNameOcrExtractionField resourceNameOcrExtractionField) {
        this.resourceNameOcrExtractionField = resourceNameOcrExtractionField;
    }

    
    @Column(name="VALUE", length=256)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="OCR_CONFIDENCE", precision=22, scale=0)
    public Double getOcrConfidence() {
        return this.ocrConfidence;
    }
    
    public void setOcrConfidence(Double ocrConfidence) {
        this.ocrConfidence = ocrConfidence;
    }

    
    @Column(name="RESULT_NAME", length=45)
    public String getResultName() {
        return this.resultName;
    }
    
    public void setResultName(String resultName) {
        this.resultName = resultName;
    }


    @Override
    public String toString() {
        return "OcrResult{" +
                "id=" + id +
                ", ocrProcess=" + ocrProcess +
                ", resourceNameOcrExtractionField=" + resourceNameOcrExtractionField +
                ", value='" + value + '\'' +
                ", ocrConfidence=" + ocrConfidence +
                ", resultName='" + resultName + '\'' +
                '}';
    }
}


