package com.fintech.oracle.dataabstraction.entities;
// Generated Nov 24, 2016 4:01:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OcrResults generated by hbm2java
 */
@Entity
@Table(name="ocr_results"
)
public class OcrResults  implements java.io.Serializable {


     private Integer id;
     private OcrExtractionField ocrExtractionField;
     private OcrProcess ocrProcess;
     private String keyedValue;
     private String idValue;
     private String idOcrConfidence;
     private String utilityBillValue;
     private String utilityBillOcrConfidence;
     private String passportViz;
     private String passportVizOcrConfidence;
     private String passportMrz;
     private String passportMrzOcrConfidence;
     private String drivingLicenseViz;
     private String drivingLicenseVizOcrConfidence;
     private String drivingLicenseMrz;
     private String drivingLicenseMrzOcrConfidence;

    public OcrResults() {
    }

	
    public OcrResults(OcrExtractionField ocrExtractionField, OcrProcess ocrProcess) {
        this.ocrExtractionField = ocrExtractionField;
        this.ocrProcess = ocrProcess;
    }
    public OcrResults(OcrExtractionField ocrExtractionField, OcrProcess ocrProcess, String keyedValue, String idValue, String idOcrConfidence, String utilityBillValue, String utilityBillOcrConfidence, String passportViz, String passportVizOcrConfidence, String passportMrz, String passportMrzOcrConfidence, String drivingLicenseViz, String drivingLicenseVizOcrConfidence, String drivingLicenseMrz, String drivingLicenseMrzOcrConfidence) {
       this.ocrExtractionField = ocrExtractionField;
       this.ocrProcess = ocrProcess;
       this.keyedValue = keyedValue;
       this.idValue = idValue;
       this.idOcrConfidence = idOcrConfidence;
       this.utilityBillValue = utilityBillValue;
       this.utilityBillOcrConfidence = utilityBillOcrConfidence;
       this.passportViz = passportViz;
       this.passportVizOcrConfidence = passportVizOcrConfidence;
       this.passportMrz = passportMrz;
       this.passportMrzOcrConfidence = passportMrzOcrConfidence;
       this.drivingLicenseViz = drivingLicenseViz;
       this.drivingLicenseVizOcrConfidence = drivingLicenseVizOcrConfidence;
       this.drivingLicenseMrz = drivingLicenseMrz;
       this.drivingLicenseMrzOcrConfidence = drivingLicenseMrzOcrConfidence;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FIELD", nullable=false)
    public OcrExtractionField getOcrExtractionField() {
        return this.ocrExtractionField;
    }
    
    public void setOcrExtractionField(OcrExtractionField ocrExtractionField) {
        this.ocrExtractionField = ocrExtractionField;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCESS", nullable=false)
    public OcrProcess getOcrProcess() {
        return this.ocrProcess;
    }
    
    public void setOcrProcess(OcrProcess ocrProcess) {
        this.ocrProcess = ocrProcess;
    }

    
    @Column(name="KEYED_VALUE", length=45)
    public String getKeyedValue() {
        return this.keyedValue;
    }
    
    public void setKeyedValue(String keyedValue) {
        this.keyedValue = keyedValue;
    }

    
    @Column(name="ID_VALUE", length=45)
    public String getIdValue() {
        return this.idValue;
    }
    
    public void setIdValue(String idValue) {
        this.idValue = idValue;
    }

    
    @Column(name="ID_OCR_CONFIDENCE", length=45)
    public String getIdOcrConfidence() {
        return this.idOcrConfidence;
    }
    
    public void setIdOcrConfidence(String idOcrConfidence) {
        this.idOcrConfidence = idOcrConfidence;
    }

    
    @Column(name="UTILITY_BILL_VALUE", length=45)
    public String getUtilityBillValue() {
        return this.utilityBillValue;
    }
    
    public void setUtilityBillValue(String utilityBillValue) {
        this.utilityBillValue = utilityBillValue;
    }

    
    @Column(name="UTILITY_BILL_OCR_CONFIDENCE", length=45)
    public String getUtilityBillOcrConfidence() {
        return this.utilityBillOcrConfidence;
    }
    
    public void setUtilityBillOcrConfidence(String utilityBillOcrConfidence) {
        this.utilityBillOcrConfidence = utilityBillOcrConfidence;
    }

    
    @Column(name="PASSPORT_VIZ", length=45)
    public String getPassportViz() {
        return this.passportViz;
    }
    
    public void setPassportViz(String passportViz) {
        this.passportViz = passportViz;
    }

    
    @Column(name="PASSPORT_VIZ_OCR_CONFIDENCE", length=45)
    public String getPassportVizOcrConfidence() {
        return this.passportVizOcrConfidence;
    }
    
    public void setPassportVizOcrConfidence(String passportVizOcrConfidence) {
        this.passportVizOcrConfidence = passportVizOcrConfidence;
    }

    
    @Column(name="PASSPORT_MRZ", length=45)
    public String getPassportMrz() {
        return this.passportMrz;
    }
    
    public void setPassportMrz(String passportMrz) {
        this.passportMrz = passportMrz;
    }

    
    @Column(name="PASSPORT_MRZ_OCR_CONFIDENCE", length=45)
    public String getPassportMrzOcrConfidence() {
        return this.passportMrzOcrConfidence;
    }
    
    public void setPassportMrzOcrConfidence(String passportMrzOcrConfidence) {
        this.passportMrzOcrConfidence = passportMrzOcrConfidence;
    }

    
    @Column(name="DRIVING_LICENSE_VIZ", length=45)
    public String getDrivingLicenseViz() {
        return this.drivingLicenseViz;
    }
    
    public void setDrivingLicenseViz(String drivingLicenseViz) {
        this.drivingLicenseViz = drivingLicenseViz;
    }

    
    @Column(name="DRIVING_LICENSE_VIZ_OCR_CONFIDENCE", length=45)
    public String getDrivingLicenseVizOcrConfidence() {
        return this.drivingLicenseVizOcrConfidence;
    }
    
    public void setDrivingLicenseVizOcrConfidence(String drivingLicenseVizOcrConfidence) {
        this.drivingLicenseVizOcrConfidence = drivingLicenseVizOcrConfidence;
    }

    
    @Column(name="DRIVING_LICENSE_MRZ", length=45)
    public String getDrivingLicenseMrz() {
        return this.drivingLicenseMrz;
    }
    
    public void setDrivingLicenseMrz(String drivingLicenseMrz) {
        this.drivingLicenseMrz = drivingLicenseMrz;
    }

    
    @Column(name="DRIVING_LICENSE_MRZ_OCR_CONFIDENCE", length=45)
    public String getDrivingLicenseMrzOcrConfidence() {
        return this.drivingLicenseMrzOcrConfidence;
    }
    
    public void setDrivingLicenseMrzOcrConfidence(String drivingLicenseMrzOcrConfidence) {
        this.drivingLicenseMrzOcrConfidence = drivingLicenseMrzOcrConfidence;
    }




}


