package com.fintech.oracle.dataabstraction.entities;
// Generated Jan 27, 2017 10:12:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourceNameOcrExtractionField generated by hbm2java
 */
@Entity
@Table(name="resource_name_ocr_extraction_field"
)
public class ResourceNameOcrExtractionField  implements java.io.Serializable {


     private Integer id;
     private OcrExtractionField ocrExtractionField;
     private ResourceName resourceName;
     private Integer minimumAcceptableOcrConfidence;

    public ResourceNameOcrExtractionField() {
    }

    public ResourceNameOcrExtractionField(OcrExtractionField ocrExtractionField, ResourceName resourceName, Integer minumumAcceptableOcrConfidence) {
       this.ocrExtractionField = ocrExtractionField;
       this.resourceName = resourceName;
       this.minimumAcceptableOcrConfidence = minumumAcceptableOcrConfidence;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ocr_extraction_field_ID")
    public OcrExtractionField getOcrExtractionField() {
        return this.ocrExtractionField;
    }
    
    public void setOcrExtractionField(OcrExtractionField ocrExtractionField) {
        this.ocrExtractionField = ocrExtractionField;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resource_name_ID")
    public ResourceName getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(ResourceName resourceName) {
        this.resourceName = resourceName;
    }

    
    @Column(name="minimum_acceptable_ocr_confidence")
    public Integer getMinimumAcceptableOcrConfidence() {
        return this.minimumAcceptableOcrConfidence;
    }
    
    public void setMinimumAcceptableOcrConfidence(Integer minimumAcceptableOcrConfidence) {
        this.minimumAcceptableOcrConfidence = minimumAcceptableOcrConfidence;
    }


}


