package com.fintech.oracle.dataabstraction.entities;
// Generated Nov 24, 2016 4:01:54 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourceMetadata generated by hbm2java
 */
@Entity
@Table(name="resource_metadata"
)
public class ResourceMetadata  implements java.io.Serializable {


     private ResourceMetadataId id;
     private Resource resource;
     private String value;

    public ResourceMetadata() {
    }

    public ResourceMetadata(ResourceMetadataId id, Resource resource, String value) {
       this.id = id;
       this.resource = resource;
       this.value = value;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="resource", column=@Column(name="RESOURCE", nullable=false) ), 
        @AttributeOverride(name="key", column=@Column(name="KEY", nullable=false, length=45) ) } )
    public ResourceMetadataId getId() {
        return this.id;
    }
    
    public void setId(ResourceMetadataId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE", nullable=false, insertable=false, updatable=false)
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resource) {
        this.resource = resource;
    }

    
    @Column(name="VALUE", nullable=false, length=45)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


