package com.fintech.oracle.dataabstraction.entities;
// Generated Dec 25, 2016 11:01:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourceMetadataId generated by hbm2java
 */
@Embeddable
public class ResourceMetadataId  implements java.io.Serializable {


     private int resource;
     private String key;

    public ResourceMetadataId() {
    }

    public ResourceMetadataId(int resource, String key) {
       this.resource = resource;
       this.key = key;
    }
   


    @Column(name="RESOURCE", nullable=false)
    public int getResource() {
        return this.resource;
    }
    
    public void setResource(int resource) {
        this.resource = resource;
    }


    @Column(name="KEY", nullable=false, length=45)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ResourceMetadataId) ) return false;
		 ResourceMetadataId castOther = ( ResourceMetadataId ) other; 
         
		 return (this.getResource()==castOther.getResource())
 && ( (this.getKey()==castOther.getKey()) || ( this.getKey()!=null && castOther.getKey()!=null && this.getKey().equals(castOther.getKey()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getResource();
         result = 37 * result + ( getKey() == null ? 0 : this.getKey().hashCode() );
         return result;
   }   


}


