package com.fintech.oracle.dataabstraction.entities;
// Generated Dec 22, 2016 11:53:40 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ResourceName generated by hbm2java
 */
@Entity
@Table(name="resource_name"
)
public class ResourceName  implements java.io.Serializable {


     private int id;
     private String name;
     private String configFilePath;

    public ResourceName() {
    }

	
    public ResourceName(int id) {
        this.id = id;
    }
    public ResourceName(int id, String name, String configFilePath) {
       this.id = id;
       this.name = name;
       this.configFilePath = configFilePath;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="CONFIG_FILE_PATH", length=50)
    public String getConfigFilePath() {
        return this.configFilePath;
    }
    
    public void setConfigFilePath(String configFilePath) {
        this.configFilePath = configFilePath;
    }




}


