package com.fintech.oracle.dataabstraction.entities;
// Generated Dec 25, 2016 11:01:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name="resource"
)
public class Resource  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private OcrProcess ocrProcess;
     private OcrProcessingStatus ocrProcessingStatus;
     private Process process;
     private ResourceName resourceName;
     private ResourceType resourceType;
     private String location;
     private String resourceIdentificationCode;
     private Set<ResourceMetadata> resourceMetadatas = new HashSet<ResourceMetadata>(0);

    public Resource() {
    }

    public Resource(Client client, OcrProcess ocrProcess, OcrProcessingStatus ocrProcessingStatus, Process process, ResourceName resourceName, ResourceType resourceType, String location, String resourceIdentificationCode, Set<ResourceMetadata> resourceMetadatas) {
       this.client = client;
       this.ocrProcess = ocrProcess;
       this.ocrProcessingStatus = ocrProcessingStatus;
       this.process = process;
       this.resourceName = resourceName;
       this.resourceType = resourceType;
       this.location = location;
       this.resourceIdentificationCode = resourceIdentificationCode;
       this.resourceMetadatas = resourceMetadatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OCR_PROCESS")
    public OcrProcess getOcrProcess() {
        return this.ocrProcess;
    }
    
    public void setOcrProcess(OcrProcess ocrProcess) {
        this.ocrProcess = ocrProcess;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OCR_PROCESSING_STATUS")
    public OcrProcessingStatus getOcrProcessingStatus() {
        return this.ocrProcessingStatus;
    }
    
    public void setOcrProcessingStatus(OcrProcessingStatus ocrProcessingStatus) {
        this.ocrProcessingStatus = ocrProcessingStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCESS")
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE_NAME")
    public ResourceName getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(ResourceName resourceName) {
        this.resourceName = resourceName;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE_TYPE")
    public ResourceType getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    
    @Column(name="LOCATION", length=128)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="RESOURCE_IDENTIFICATION_CODE", length=40)
    public String getResourceIdentificationCode() {
        return this.resourceIdentificationCode;
    }
    
    public void setResourceIdentificationCode(String resourceIdentificationCode) {
        this.resourceIdentificationCode = resourceIdentificationCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resource")
    public Set<ResourceMetadata> getResourceMetadatas() {
        return this.resourceMetadatas;
    }
    
    public void setResourceMetadatas(Set<ResourceMetadata> resourceMetadatas) {
        this.resourceMetadatas = resourceMetadatas;
    }


}


